# General settings
name: 'sbm'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch

root_path: null # Should be absolute path to data directory

h1_model: null # Use absolute paths
glue_model: null # Use absolute paths
h2_model: null # Use absolute paths

samples_to_generate: 200
h1_batch_size: 16
glue_batch_size: 5
