# Model settings
type: 'discrete'
transition: 'marginal'                          # uniform or marginal
model: 'graph_tf'
diffusion_steps: 100
diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2'
n_layers: 4


extra_features:  'cycles'                  # default for hierarchical diffusion 'cycles'        # 'all', 'cycles', 'eigenvalues' or null

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
# At the moment (03/08), y contains quite little information
hidden_mlp_dims: {'X': 32, 'E': 32, 'y': 32}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 32, 'de': 32, 'dy': 32, 'n_head': 8, 'dim_ffX': 32, 'dim_ffE': 32, 'dim_ffy': 32}

lambda_train: [5, 0]
