name: 'cora'            # ego, ego_positional
datadir: 'data/cora/'
h: 1
random_subset: null
pin_memory: False
subsample: False
resolution: 3
max_size: 500 # for non-subsample is reasonable
regime: 'majority' # alt: 'majority' for graph classing by majority node class, 'size' for number of junctions TODO: add similar to sampling
dataset_testing: False
